<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType><TargetFramework>net10.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings><Nullable>enable</Nullable>
    <RuntimeFrameworkVersion>10.0.11</RuntimeFrameworkVersion><IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract><EnableCompressionInSingleFile>true</EnableCompressionInSingleFile><DebugType>embedded</DebugType><Version>0.5.1</Version><AssemblyName>RootedAndroidGameVM.Cli</AssemblyName>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier><SelfContained>true</SelfContained><PublishSingleFile>true</PublishSingleFile>
  </PropertyGroup>
  <ItemGroup><ProjectReference Include="..\RootedAndroidGameVM.Core\RootedAndroidGameVM.Core.csproj" /></ItemGroup>
</Project>
