namespace RootedAndroidGameVM.Core.Debugging;

public sealed record DebugCommandDescription(string Name, string Purpose, string Arguments);
public static class DebugCommandCatalog
{
    public static readonly DebugCommandDescription[] Commands =
    [
        new("status", "当前实例状态", "{}"),
        new("memory.snapshot", "宿主余量、产品进程工作集/私有提交与归属", "{}"),
        new("capabilities", "能力与约束", "{}"),
        new("schema", "命令说明", "{}"),
        new("start", "启动当前安卓", "{}"),
        new("stop", "同步并停止安卓", "{}"),
        new("window.focus", "打开产品安卓窗口", "{}"),
        new("screen", "保存原始 PNG 和观察编号", "{}"),
        new("preview", "GUI 二进制预览；第二帧为 PNG", "{}"),
        new("preview.benchmark", "预览开销与内存采样", "{\"frames\":20}"),
        new("frames.sample", "应用实际呈现帧时间", "{\"package\":\"me.mugzone.emiria\",\"seconds\":15}"),
        new("input", "按观察编号运行输入序列", "{\"observation\":\"id\",\"frames\":[{\"atMs\":0,\"touches\":[{\"id\":0,\"x\":100,\"y\":100,\"pressure\":1}]}]}"),
        new("release", "取消输入并释放触点", "{}"),
        new("wake", "唤醒并验证状态", "{}"),
        new("key", "Android 键码", "{\"key\":\"KEYCODE_BACK\"}"),
        new("clipboard", "读取或写入安卓剪贴板", "{\"text\":\"可选写入内容\"}"),
        new("apps", "第三方应用列表", "{}"),
        new("apk.inspect", "APK 版本、包名与 ABI", "{\"path\":\"C:\\\\input\\\\app.apk\"}"),
        new("install", "保留数据安装并启动，不降级", "{\"path\":\"C:\\\\input\\\\app.apk\"}"),
        new("launch", "启动并观察进程；waitForActivity可等待前台Activity，均不代表页面可操作", "{\"package\":\"me.mugzone.emiria\",\"waitForActivity\":true}"),
        new("app.observe", "保存进程与前台Activity观察证据和时间", "{\"package\":\"me.mugzone.emiria\"}"),
        new("force-stop", "停止应用", "{\"package\":\"me.mugzone.emiria\"}"),
        new("uninstall", "明确确认后卸载普通应用", "{\"package\":\"test.app\",\"confirm\":true}"),
        new("files.list", "浏览范围内目录", "{\"package\":\"test.app\",\"scope\":\"external\",\"remote\":\"files\"}"),
        new("files.push", "暂存、校验与备份后上传", "{\"scope\":\"external\",\"remote\":\"files/a.bin\",\"local\":\"C:\\\\input\\\\a.bin\"}"),
        new("files.pull", "校验后下载文件", "{\"scope\":\"external\",\"remote\":\"files/a.bin\",\"local\":\"C:\\\\output\\\\a.bin\"}"),
        new("files.export", "受控导出选中目录", "{\"scope\":\"private\",\"remote\":\"files\",\"local\":\"C:\\\\output\"}"),
        new("files.diff", "目录差异比较", "{\"scope\":\"external\",\"remote\":\"files/qa\",\"local\":\"C:\\\\qa\"}"),
        new("files.sync", "同步变化文件并保留额外文件", "{\"scope\":\"external\",\"remote\":\"files/qa\",\"local\":\"C:\\\\qa\"}"),
        new("malody.import", "由 Malody 导入并核验；续作使用{importId:原编号}替代path，不再上传", "{\"path\":\"C:\\\\input\\\\content.msp\"}"),
        new("malody.reload", "重启应用后导入并验证解包", "{\"path\":\"C:\\\\input\\\\content.mcz\"}"),
        new("logs", "跟随应用 PID 的日志", "{\"package\":\"test.app\",\"seconds\":30}"),
        new("metrics", "内存、CPU 与可用诊断依据", "{\"package\":\"test.app\"}"),
        new("record", "录屏，无音频", "{\"seconds\":15}"),
        new("trace", "系统追踪", "{\"seconds\":15}"),
        new("checkpoint.create", "停机磁盘检查点", "{}"),
        new("checkpoint.list", "检查点列表", "{}"),
        new("checkpoint.restore", "验证后恢复并冷启动", "{\"id\":\"checkpoint-id\"}"),
        new("checkpoint.recover", "恢复中断切换", "{}"),
        new("runtime.inspect", "请求配置与实际显示分开报告", "{}"),
        new("runtime.configure", "停机后保存配置", "{\"profile\":{\"renderer\":\"host\",\"width\":1920,\"height\":1080,\"density\":240,\"refreshRate\":120,\"memoryMb\":3072,\"cpuCores\":4,\"desktopDisplay\":true}}"),
        new("display.desktop", "切换已备份的模拟设备外观", "{\"enabled\":true}"),
        new("performance.set", "兼容旧版图形档位", "{\"profile\":\"HighPerformance\"}"),
        new("shell", "显式普通 Shell", "{\"script\":\"id\",\"timeoutSeconds\":10}"),
        new("root-shell", "显式 Root Shell", "{\"script\":\"id\",\"timeoutSeconds\":10}"),
        new("test", "顺序测试请求，不允许嵌套恢复", "{\"steps\":[{\"command\":\"screen\"}]}"),
        new("grpc.audit", "检查认证拒绝与回环连接", "{}"),
        new("licenses", "随程序附带的许可证", "{}"),
        new("jobs", "任务列表", "{}"),
        new("job", "查询并续期输入任务", "{\"id\":\"job-id\"}"),
        new("cancel", "取消任务", "{\"id\":\"job-id\"}"),
        new("quiesce", "停止调试任务但保留安卓", "{}"),
        new("shutdown", "安卓已停止时退出协调进程", "{}")
    ];
}
